version: '3.5'

services:
  apiacbrliblaraveldev:
    build: .
    container_name: apiacbrliblaraveldev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - apiacbrliblaraveldev

networks:
  backend:
    name: apiacbrliblaravelnetwork
